# Generated by Django 5.0.6 on 2024-07-15 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_date', models.DateField()),
                ('monitor_name', models.CharField(max_length=200)),
                ('monitor_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_practices', models.TextField()),
                ('effectiveness', models.CharField(max_length=200)),
                ('new_measures', models.TextField()),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoringData.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('weather_conditions', models.CharField(max_length=200)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoringData.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseMonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_presence', models.BooleanField()),
                ('disease_type', models.CharField(max_length=200)),
                ('disease_name', models.CharField(max_length=200)),
                ('disease_severity', models.CharField(max_length=200)),
                ('disease_symptoms', models.TextField()),
                ('disease_spread', models.CharField(max_length=200)),
                ('disease_incidence', models.FloatField()),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoringData.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='DataCollectionTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traps_used', models.CharField(max_length=200)),
                ('sensors_deployed', models.CharField(max_length=200)),
                ('survey_methods', models.CharField(max_length=200)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoringData.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='CropPlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_plant_type', models.CharField(max_length=200)),
                ('variety', models.CharField(max_length=200)),
                ('growth_stage', models.CharField(max_length=200)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoringData.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_video', models.FileField(upload_to='attachments/')),
                ('notes', models.TextField()),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoringData.monitoring')),
            ],
        ),
        migrations.CreateModel(
            name='PestMonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_presence', models.BooleanField()),
                ('pest_type', models.CharField(max_length=200)),
                ('pest_name', models.CharField(max_length=200)),
                ('pest_density', models.IntegerField()),
                ('pest_damage', models.TextField()),
                ('pest_life_stage', models.CharField(max_length=200)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoringData.monitoring')),
            ],
        ),
    ]
