# Generated by Django 5.0.6 on 2024-07-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('inspector', models.CharField(max_length=200)),
                ('disease_identified', models.CharField(max_length=200)),
                ('region_of_origin', models.CharField(max_length=200)),
                ('country_heading', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
                ('test_conducted', models.CharField(max_length=200)),
                ('chemical_used', models.CharField(max_length=200)),
                ('volume_used', models.FloatField()),
                ('total_charge', models.FloatField()),
                ('station', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Rejected', 'Rejected')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('highest_education_level', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('inspection_station', models.CharField(max_length=200)),
                ('certifications', models.TextField()),
            ],
        ),
    ]
