# Generated by Django 5.0.6 on 2024-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantHealth', '0002_permit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='customer_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='permit',
            name='customer_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='permit',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permit',
            name='chemical_used',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='country_heading',
            field=models.CharField(default='Unknown Country', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='customer_name',
            field=models.CharField(default='Unknown Customer', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='disease_identified',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='inspector',
            field=models.CharField(default='Unknown Inspector', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='permit',
            name='region_of_origin',
            field=models.CharField(default='Unknown Region', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='station',
            field=models.CharField(default='Unknown Station', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Rejected', 'Rejected')], default='Pass', max_length=10),
        ),
        migrations.AlterField(
            model_name='permit',
            name='test_conducted',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='permit',
            name='total_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='permit',
            name='volume_used',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='certifications',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='user',
            name='highest_education_level',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='inspection_station',
            field=models.CharField(default='Unknown Station', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unknown User', max_length=200),
        ),
    ]
